CREATE TABLE IF NOT EXISTS users (
	name VARCHAR(255) NOT NULL,
	user_id INTEGER AUTO_INCREMENT NOT NULL,
	PRIMARY KEY (user_id),
	KEY (name)
);

CREATE TABLE IF NOT EXISTS key_pairs (
	user_id INTEGER NOT NULL,
	key_id VARCHAR(255) NOT NULL,
	secret_key VARCHAR(255) NOT NULL,
	mark TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (user_id, key_id),
	KEY (key_id)
);

CREATE TABLE IF NOT EXISTS key_values (
	user_id INTEGER NOT NULL,
	k VARCHAR(2048),
	v LONGBLOB,
	mark TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	version VARCHAR(255) NOT NULL,
	PRIMARY KEY (user_id, k(128))
);