/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class core_crypt_PBEPlatform */

#ifndef _Included_core_crypt_PBEPlatform
#define _Included_core_crypt_PBEPlatform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     core_crypt_PBEPlatform
 * Method:    generate
 * Signature: (Ljava/lang/String;[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_core_crypt_PBEPlatformNative_generate
  (JNIEnv *, jclass, jstring, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
